python infer_neural_fca.py \
  --root_dir "/mnt/d/datasets/libri_test_2sp_6ch_8k" \
  --split test \
  --save_dir "/mnt/f/libri_separation_outputs/neural-fca" \
  --ckpt exp/neural-fca/last.pt \
  --num_speakers 2 \
  --select_channels 0,2,4 \
  --n_samples 500 \
  --verbose \
  --compute_pesq \
  --compute_estoi \
  --n_fft 512 \
  --hop 128 \
  --n_iter 30 \
  --n_ziter 50 \
  --n_hiter 5