#!/usr/bin/env bash
set -euo pipefail

python separate.py \
  --config_path 'conf/conf_libritts_unet1d_attention_8k.yaml' \
  --architecture 'unet_1d_att' \
  --checkpoint 'weights-139999.pt' \
  --root_dir "/mnt/d/datasets/libri_test_2sp_6ch_8k" \
  --num_speakers 2 \
  --reverb 1 \
  --n_channels 3 \
  --num_steps 400 \
  --max_trials 5 \
  --snr_stop 35 \
  --max_trials2 2 \
  --snr_stop2 14 \
  --max_trials3 5 \
  --snr_stop3 10 \
  --sigma_max 0.8 \
  --rho 10 \
  --schurn 30 \
  --xi 2.0 \
  --n_fft 512 \
  --hop_length 128 \
  --lambda_reg 0.002 \
  --n_frames_past 13 \
  --n_frames_future 0 \
  --fcp_epsilon 0.001 \
  --ref_loss_weight 0.3 \
  --ref_loss_snr_threshold 20 \
  --ref_loss_max_step 200 \
  --use_warm_initialization 1 \
  --warm_initialization_rescale 1 \
  --warm_initialization_sigma 0.057 \
  --initialized_filter_step 100 \
  --save_dir "/mnt/f/libri_separation_outputs" \
  --n_samples 500 \
  --blind 1 \
  --start_sample 0